### ISSUE TITLE
Additional molecule (SO2)

### ISSUE THREAD

**Issue by pirg** [astropenguin/ndradex#5]
Would it be possible to add the SO2 data from the LAMDA database ? https://home.strw.leidenuniv.nl/~moldata/SO2.html

**Comment by astropenguin** [comment]
Hi @pirg, SO2 are currently excluded from [List of available LAMDA datafiles and transitions](https://github.com/astropenguin/ndradex/wiki/List-of-available-LAMDA-datafiles-and-transitions) because the format of data files is something wrong, which fails to read them using [astroquery](https://astroquery.readthedocs.io/en/latest/lamda/lamda.html) within ndRADEX.

Now I am asking LAMDA people to fix them.
https://twitter.com/astropengu_in/status/1196374442194038785

I think the current workaround is (1) download SO2 data files in local, (2) edit them to fix the format, and (3) use the local data files by [setting datafile aliases](https://github.com/astropenguin/ndradex#setting-datafile-aliases).

**Comment by astropenguin** [comment]
The SO2 high-T datafile was fixed by the LAMDA database team!

> Removed newlines from SO2 high-T datafile which caused ndRadex (but not classic Radex) to crash.
> Thanks Akio Tanaguchi & Valentine Wakelam
> &mdash; Lamda Database (@lamda_database) [September 29, 2020](https://twitter.com/lamda_database/status/1310946813650886657)
